apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probesdemo
  name: probesdemo
spec:
  selector:
    matchLabels:
      app: probesdemo
  template:
    metadata:
      labels:
        app: probesdemo
    spec:
      initContainers:
        - name: 
      containers:
      - image: eiximenis/probesdemo
        name: probesdemo
        ports:
        - containerPort: 80
        livenessProbe:
          periodSeconds: 20
          httpGet:
            path: /live
            port: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 200Mi
            
