apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-07T17:03:25Z"
  labels:
    run: wp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:containers:
          k:{"name":"wp"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"WORDPRESS_DB_HOST"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"WORDPRESS_DB_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"WORDPRESS_DB_PASSWORD"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"WORDPRESS_DB_USER"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":80,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl-run
    operation: Update
    time: "2021-04-07T17:03:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"172.17.0.5"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2021-04-07T17:03:26Z"
  name: wp
  namespace: default
  resourceVersion: "28651"
  uid: 088a8839-567b-47d2-a9bd-307716e41b21
spec:
  containers:
  - env:
    - name: WORDPRESS_DB_HOST
      value: 172.17.0.4
    - name: WORDPRESS_DB_NAME
      value: lcwp
    - name: WORDPRESS_DB_USER
      value: eiximenis
    - name: WORDPRESS_DB_PASSWORD
      value: Pa+a+a
    image: wordpress:php7.2
    imagePullPolicy: IfNotPresent
    name: wp
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rnxq9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-rnxq9
    secret:
      defaultMode: 420
      secretName: default-token-rnxq9
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-07T17:03:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-07T17:03:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-07T17:03:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-07T17:03:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://668ae1cfa0e78560b49510a9688f7d2067ab8d182a5aa223915c55d2514f43e7
    image: wordpress:php7.2
    imageID: docker-pullable://wordpress@sha256:e0c750a3b9fb4f4db5cd7485ec19fb4524e75cdeb566483cb13c6157935f63b7
    lastState: {}
    name: wp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-04-07T17:03:25Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2021-04-07T17:03:25Z"
