apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wpandmysql
  name: wpandmysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: my-secret-pw
    - name: MYSQL_DATABASE
      value: lcwp
    - name: MYSQL_USER
      value: eiximenis
    - name: MYSQL_PASSWORD
      value: Pa+a+a
    image: mysql:5
    name: mysql
    ports:
    - containerPort: 3306
  - name: wp
    image: wordpress:php7.2
    env:
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_USER
      value: eiximenis
    - name: WORDPRESS_DB_PASSWORD
      value: Pa+a+a
    - name: WORDPRESS_DB_NAME
      value: lcwp
    ports:
    - containerPort: 80
