apiVersion: v1
kind: Pod
metadata:
  labels:
    creado-por: edu
    run: helloworld
  name: helloworld
  namespace: default
spec:
  containers:
  - image: eiximenis/go-hello-world
    imagePullPolicy: Always
    name: hello
    ports:
    - containerPort: 80
      protocol: TCP
