apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    creado-por: edu
    run: helloworld
  name: hellosvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    run: helloworld
  type: LoadBalancer
status:
  loadBalancer: {}
